apiVersion: apps/v1
kind: Deployment
metadata:
  name: fplbot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fplbot
  template:
    metadata:
      labels:
        app: fplbot
    spec:
      containers:
        - image: dcoskun/fplbot
          name: fplbot
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_TOKEN
              value: ${TELEGRAM_TOKEN}
            - name: TELEGRAM_CHAT_IDS
              value: "${TELEGRAM_CHAT_IDS}"
